# Generated by Django 5.2.1 on 2025-11-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '--BKO-Permission--',
                'verbose_name_plural': '--BKO-Permissions--',
                'permissions': [('BKO', 'Permission'), ('Importar', 'importar')],
            },
        ),
    ]
