# Generated by Django 5.2.1 on 2025-11-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalpermissions',
            options={'permissions': [('BKO', 'permission BKO'), ('Importar', 'importar')], 'verbose_name': '--BKO-Permission--', 'verbose_name_plural': '--BKO-Permissions--'},
        ),
    ]
