from django.urls import path

from crm.views import (
    ajax_board_access_delete,
    ajax_board_access_update,
    ajax_board_column_update,
    ajax_board_delete,
    ajax_board_reorder_columns,
    ajax_crm_lookups,
    ajax_client_delete,
    ajax_contract_file_delete,
    ajax_contract_file_upload,
    ajax_health,
    ajax_project_member_delete,
    ajax_project_member_update,
    ajax_project_delete,
    ajax_recurrence_delete,
    ajax_settings_delete,
    ajax_status_tasks_reorder,
    ajax_task_assign,
    ajax_task_assignee_delete,
    ajax_task_assignee_update,
    ajax_task_attachment,
    ajax_task_comment,
    ajax_task_delete,
    ajax_task_link_delete,
    ajax_task_links,
    ajax_task_move,
    ajax_task_move_history,
    ajax_task_subtask,
    ajax_task_watch,
    ajax_task_watcher_add,
    ajax_task_watcher_delete,
    alert_list,
    billing_edit,
    billing_list,
    billing_new,
    board_access,
    board_edit,
    board_kanban,
    board_list,
    board_new,
    board_settings,
    client_detail,
    client_edit,
    client_list,
    client_new,
    contract_detail,
    contract_edit,
    contract_list,
    contract_new,
    dashboard,
    project_detail,
    project_edit,
    project_list,
    project_members,
    project_new,
    project_tasks,
    recurrence_detail,
    recurrence_edit,
    recurrence_list,
    recurrence_new,
    settings_index,
    settings_priorities,
    settings_priority_edit,
    settings_priority_new,
    settings_service_type_edit,
    settings_service_type_new,
    settings_service_types,
    settings_status_task_edit,
    settings_status_task_new,
    settings_status_tasks,
    task_calendar,
    task_detail,
    task_edit,
    task_list,
    task_my,
    task_new,
    validate_context,
    permissions_list,
    permissions_user,
)

app_name = 'crm'

urlpatterns = [
    path('crm/', dashboard, name='dashboard'),
    path('crm/clients/', client_list, name='client_list'),
    path('crm/clients/new/', client_new, name='client_new'),
    path('crm/clients/<int:gai_id>/', client_detail, name='client_detail'),
    path('crm/clients/<int:gai_id>/edit/', client_edit, name='client_edit'),
    path('crm/ajax/clients/<int:gai_id>/delete/', ajax_client_delete, name='ajax_client_delete'),
    path('crm/contracts/', contract_list, name='contract_list'),
    path('crm/contracts/new/', contract_new, name='contract_new'),
    path('crm/contracts/<uuid:contract_id>/', contract_detail, name='contract_detail'),
    path('crm/contracts/<uuid:contract_id>/edit/', contract_edit, name='contract_edit'),
    path(
        'crm/ajax/contracts/<uuid:contract_id>/files/',
        ajax_contract_file_upload,
        name='ajax_contract_file_upload',
    ),
    path(
        'crm/ajax/contracts/<uuid:contract_id>/files/<uuid:file_id>/delete/',
        ajax_contract_file_delete,
        name='ajax_contract_file_delete',
    ),
    path('crm/billing/', billing_list, name='billing_list'),
    path('crm/billing/new/', billing_new, name='billing_new'),
    path('crm/billing/<uuid:record_id>/edit/', billing_edit, name='billing_edit'),
    path('crm/alerts/', alert_list, name='alert_list'),
    path('crm/tasks/', task_list, name='task_list'),
    path('crm/tasks/my/', task_my, name='task_my'),
    path('crm/tasks/calendar/', task_calendar, name='task_calendar'),
    path('crm/tasks/recurrences/', recurrence_list, name='recurrence_list'),
    path('crm/tasks/recurrences/new/', recurrence_new, name='recurrence_new'),
    path('crm/tasks/recurrences/<uuid:recurrence_id>/', recurrence_detail, name='recurrence_detail'),
    path('crm/tasks/recurrences/<uuid:recurrence_id>/edit/', recurrence_edit, name='recurrence_edit'),
    path('crm/tasks/new/', task_new, name='task_new'),
    path('crm/tasks/<uuid:task_id>/', task_detail, name='task_detail'),
    path('crm/tasks/<uuid:task_id>/edit/', task_edit, name='task_edit'),
    path('crm/ajax/tasks/<uuid:task_id>/move/', ajax_task_move, name='ajax_task_move'),
    path('crm/ajax/tasks/<uuid:task_id>/assign/', ajax_task_assign, name='ajax_task_assign'),
    path(
        'crm/ajax/tasks/<uuid:task_id>/assignees/<uuid:assignee_id>/',
        ajax_task_assignee_update,
        name='ajax_task_assignee_update',
    ),
    path(
        'crm/ajax/tasks/<uuid:task_id>/assignees/<uuid:assignee_id>/remove/',
        ajax_task_assignee_delete,
        name='ajax_task_assignee_delete',
    ),
    path('crm/ajax/tasks/<uuid:task_id>/comments/', ajax_task_comment, name='ajax_task_comment'),
    path('crm/ajax/tasks/<uuid:task_id>/attachments/', ajax_task_attachment, name='ajax_task_attachment'),
    path('crm/ajax/tasks/<uuid:task_id>/watch/', ajax_task_watch, name='ajax_task_watch'),
    path('crm/ajax/tasks/<uuid:task_id>/watchers/', ajax_task_watcher_add, name='ajax_task_watcher_add'),
    path(
        'crm/ajax/tasks/<uuid:task_id>/watchers/<uuid:watcher_id>/remove/',
        ajax_task_watcher_delete,
        name='ajax_task_watcher_delete',
    ),
    path('crm/ajax/tasks/<uuid:task_id>/links/', ajax_task_links, name='ajax_task_links'),
    path(
        'crm/ajax/tasks/<uuid:task_id>/links/<uuid:link_id>/remove/',
        ajax_task_link_delete,
        name='ajax_task_link_delete',
    ),
    path(
        'crm/ajax/tasks/<uuid:task_id>/move-history/',
        ajax_task_move_history,
        name='ajax_task_move_history',
    ),
    path('crm/ajax/tasks/<uuid:task_id>/subtasks/', ajax_task_subtask, name='ajax_task_subtask'),
    path('crm/ajax/tasks/<uuid:task_id>/delete/', ajax_task_delete, name='ajax_task_delete'),
    path('crm/projects/', project_list, name='project_list'),
    path('crm/projects/new/', project_new, name='project_new'),
    path('crm/projects/<uuid:project_id>/', project_detail, name='project_detail'),
    path('crm/projects/<uuid:project_id>/edit/', project_edit, name='project_edit'),
    path('crm/projects/<uuid:project_id>/tasks/', project_tasks, name='project_tasks'),
    path('crm/projects/<uuid:project_id>/members/', project_members, name='project_members'),
    path(
        'crm/ajax/projects/<uuid:project_id>/members/<uuid:member_id>/',
        ajax_project_member_update,
        name='ajax_project_member_update',
    ),
    path(
        'crm/ajax/projects/<uuid:project_id>/members/<uuid:member_id>/delete/',
        ajax_project_member_delete,
        name='ajax_project_member_delete',
    ),
    path('crm/ajax/projects/<uuid:project_id>/delete/', ajax_project_delete, name='ajax_project_delete'),
    path(
        'crm/ajax/tasks/recurrences/<uuid:recurrence_id>/delete/',
        ajax_recurrence_delete,
        name='ajax_recurrence_delete',
    ),
    path('crm/boards/', board_list, name='board_list'),
    path('crm/boards/new/', board_new, name='board_new'),
    path('crm/boards/<uuid:board_id>/', board_kanban, name='board_kanban'),
    path('crm/boards/<uuid:board_id>/edit/', board_edit, name='board_edit'),
    path('crm/boards/<uuid:board_id>/settings/', board_settings, name='board_settings'),
    path('crm/boards/<uuid:board_id>/access/', board_access, name='board_access'),
    path('crm/ajax/boards/<uuid:board_id>/delete/', ajax_board_delete, name='ajax_board_delete'),
    path(
        'crm/ajax/boards/<uuid:board_id>/reorder-columns/',
        ajax_board_reorder_columns,
        name='ajax_board_reorder_columns',
    ),
    path(
        'crm/ajax/boards/<uuid:board_id>/columns/<uuid:column_id>/',
        ajax_board_column_update,
        name='ajax_board_column_update',
    ),
    path(
        'crm/ajax/boards/<uuid:board_id>/access/<uuid:access_id>/',
        ajax_board_access_update,
        name='ajax_board_access_update',
    ),
    path(
        'crm/ajax/boards/<uuid:board_id>/access/<uuid:access_id>/delete/',
        ajax_board_access_delete,
        name='ajax_board_access_delete',
    ),
    path('crm/settings/', settings_index, name='settings_index'),
    path('crm/settings/service-types/', settings_service_types, name='settings_service_types'),
    path('crm/settings/service-types/new/', settings_service_type_new, name='settings_service_type_new'),
    path(
        'crm/settings/service-types/<int:record_id>/edit/',
        settings_service_type_edit,
        name='settings_service_type_edit',
    ),
    path('crm/settings/priorities/', settings_priorities, name='settings_priorities'),
    path('crm/settings/priorities/new/', settings_priority_new, name='settings_priority_new'),
    path(
        'crm/settings/priorities/<uuid:record_id>/edit/',
        settings_priority_edit,
        name='settings_priority_edit',
    ),
    path('crm/settings/status-tasks/', settings_status_tasks, name='settings_status_tasks'),
    path('crm/settings/status-tasks/new/', settings_status_task_new, name='settings_status_task_new'),
    path(
        'crm/settings/status-tasks/<uuid:record_id>/edit/',
        settings_status_task_edit,
        name='settings_status_task_edit',
    ),
    path('crm/settings/permissions/', permissions_list, name='permissions_list'),
    path('crm/settings/permissions/<int:user_id>/', permissions_user, name='permissions_user'),
    path(
        'crm/ajax/settings/status-tasks/reorder/',
        ajax_status_tasks_reorder,
        name='ajax_status_tasks_reorder',
    ),
    path(
        'crm/ajax/settings/<str:resource>/<uuid:record_id>/delete/',
        ajax_settings_delete,
        name='ajax_settings_delete',
    ),
    path('crm/ajax/lookups/crm/', ajax_crm_lookups, name='ajax_crm_lookups'),
    path('crm/ajax/health/', ajax_health, name='ajax_health'),
    path('crm/diagnostic/validate-context/', validate_context, name='validate_context'),
]
