from .view_lista_projetos import lista_projetos
from .view_detalhe_projeto import detalhe_projeto
from .view_form_projeto import form_projeto
from .view_membros_projeto import membros_projeto
from .view_tasks_projeto import tasks_projeto
from .views_boards.view_lista_boards import lista_boards
from .views_boards.view_kanban_board import kanban_board
from .views_boards.view_form_board import form_board
from .views_boards.view_acesso_board import acesso_board
from .views_boards.view_colunas_board import colunas_board
from .views_ajax.view_ajax_boards import ajax_reorder_columns
