# Generated by Django 5.2.1 on 2025-05-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Romaneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('codigo_rastreio', models.CharField(blank=True, max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRomaneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100)),
                ('chamado', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=10)),
                ('hora', models.CharField(max_length=10)),
                ('usuario', models.CharField(max_length=100)),
                ('filial', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('romaneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='logistica.romaneio')),
            ],
        ),
    ]
