# Generated by Django 5.2.1 on 2025-07-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_pontoatendimentoinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permissão de Usuario',
                'verbose_name_plural': 'Permissões de Usuários',
                'permissions': [('pode_gerenciar_usuarios', 'Pode gerenciar usuários'), ('pode_gerenciar_grupos', 'Pode gerenciar grupos')],
            },
        ),
    ]
