# Generated by Django 5.2.1 on 2025-07-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_permissoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissoes',
            options={'permissions': [('pode_gerenciar_usuarios', 'Pode gerenciar usuários'), ('pode_gerenciar_grupos', 'Pode gerenciar grupos')], 'verbose_name': 'Transporte | Permissão de Usuario', 'verbose_name_plural': 'Transporte | Permissões de Usuários'},
        ),
    ]
