# Generated by Django 5.2.1 on 2025-07-30 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('logistica', '0004_alter_permissoes_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissoes',
            new_name='Permition',
        ),
        migrations.CreateModel(
            name='GroupAditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('CEP', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('telefone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 1')),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes_adicionais', to='auth.group')),
            ],
        ),
    ]
