# Generated by Django 5.2.1 on 2025-08-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permition',
            options={'permissions': [('pode_gerenciar_usuarios', 'Pode gerenciar usuários'), ('pode_gerenciar_grupos', 'Pode gerenciar grupos'), ('pode_visualizar_telas', 'Pode visualizar telas')], 'verbose_name': 'Transporte | Permissão de Usuario', 'verbose_name_plural': 'Transporte | Permissões de Usuários'},
        ),
    ]
