# Generated by Django 5.2.1 on 2025-08-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_alter_permition_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permition',
            new_name='PermissaoUsuarioDummy',
        ),
    ]
