# Generated by Django 5.2.1 on 2025-08-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0009_rename_permition_permissaousuariodummy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissaousuariodummy',
            options={'permissions': [('pode_gerenciar_usuarios', 'Pode gerenciar usuários'), ('pode_gerenciar_grupos', 'Pode gerenciar grupos'), ('usuario_credenciado', 'Usuário credenciado')], 'verbose_name': 'Transporte | Permissão de Usuario', 'verbose_name_plural': 'Transporte | Permissões de Usuários'},
        ),
    ]
