# Generated by Django 5.2.1 on 2025-08-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0010_alter_permissaousuariodummy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissaousuariodummy',
            options={'permissions': [('pode_gerenciar_usuarios', 'Pode gerenciar usuários'), ('pode_gerenciar_grupos', 'Pode gerenciar grupos'), ('usuario_credenciado', 'Usuário credenciado'), ('pode_acessar_fulfillment', 'Pode acessar Fulfillment')], 'verbose_name': 'Transporte | Permissão de Usuario', 'verbose_name_plural': 'Transporte | Permissões de Usuários'},
        ),
    ]
