# Generated by Django 5.2.1 on 2025-08-01 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0012_remove_groupaditionalinformation_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aditional_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designacoes', to='logistica.groupaditionalinformation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='designacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Designação de Usuário',
                'verbose_name_plural': 'Designações de Usuários',
            },
        ),
    ]
