# Generated by Django 5.2.1 on 2025-08-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('logistica', '0013_userdesignation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupaditionalinformation',
            name='group',
        ),
        migrations.AddField(
            model_name='groupaditionalinformation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informacoes_adicionais', to='auth.group'),
        ),
    ]
