# Generated by Django 5.2.1 on 2025-08-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0014_remove_groupaditionalinformation_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDesignation',
        ),
    ]
