# Generated by Django 5.2.1 on 2025-08-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0017_remove_groupaditionalinformation_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaditionalinformation',
            name='nome_PA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do PA'),
        ),
    ]
