# Generated by Django 5.2.1 on 2025-08-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0018_groupaditionalinformation_nome_pa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupaditionalinformation',
            name='nome_PA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
