# Generated by Django 5.2.1 on 2025-08-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0019_alter_groupaditionalinformation_nome_pa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupaditionalinformation',
            old_name='nome_PA',
            new_name='nome',
        ),
    ]
