# Generated by Django 5.2.1 on 2025-08-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('logistica', '0020_rename_nome_pa_groupaditionalinformation_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
    ]
