# Generated by Django 5.2.1 on 2025-08-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0022_userdesignation_delete_solicitacaocadastro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissaousuariodummy',
            options={'permissions': [('pode_gerenciar_usuarios', 'Pode gerenciar usuários'), ('pode_gerenciar_grupos', 'Pode gerenciar grupos'), ('usuario_credenciado', 'Usuário credenciado'), ('pode_acessar_fulfillment', 'Pode acessar Fulfillment'), ('usuario_de_backoffice', 'Usuário de Backoffice'), ('usuario_de_logistica', 'Usuário de Logística'), ('usuario_de_transporte', 'Usuário de Transporte'), ('usuario_de_TI', 'Usuário de TI'), ('usuario_de_financeiro', 'Usuário de Financeiro'), ('usuario_de_PA', 'Usuário de PA'), ('usuario_administrador', 'Usuário Administrador'), ('usuario_de_gerencia', 'Usuário de Gerência'), ('usuario_de_supervisao', 'Usuário de Supervisão')], 'verbose_name': 'Transporte | Permissão de Usuario', 'verbose_name_plural': 'Transporte | Permissões de Usuários'},
        ),
    ]
