# Generated by Django 5.2.1 on 2025-08-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0025_alter_permissaousuariodummy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissaousuariodummy',
            options={'permissions': [('lastmile_b2c', 'LastMile (B2C)')], 'verbose_name': '--Personalizada--', 'verbose_name_plural': '--Personalizadas--'},
        ),
    ]
