# Generated by Django 5.2.1 on 2025-08-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0027_alter_permissaousuariodummy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaditionalinformation',
            name='cod_iata',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Iata'),
        ),
        migrations.AddField(
            model_name='groupaditionalinformation',
            name='sales_channel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sales Channel'),
        ),
    ]
