# Generated by Django 5.2.1 on 2025-08-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0028_groupaditionalinformation_cod_iata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupaditionalinformation',
            name='cod_iata',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código IATA'),
        ),
    ]
