# Generated by Django 5.2.1 on 2025-08-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0029_alter_groupaditionalinformation_cod_iata'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaditionalinformation',
            name='deposito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Depósito'),
        ),
    ]
