# Generated by Django 5.2.1 on 2025-08-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0031_remove_userprofile_cpf_userprofile_avatar_and_more'),
    ]

    operations = [
    ]
