# Generated by Django 5.2.1 on 2025-08-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0032_auto_20250825_1132'),
    ]

    operations = [
    ]
