# Generated by Django 5.2.1 on 2025-08-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0034_userprofile_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissaousuariodummy',
            options={'permissions': [('lastmile_b2c', 'LastMile (B2C)'), ('entrada_flfm', 'Entrada (Fulfillment)'), ('pode_gerenciar_filiais', 'Pode Gerenciar Filiais')], 'verbose_name': '--Personalizada--', 'verbose_name_plural': '--Personalizadas--'},
        ),
    ]
