# Generated by Django 5.2.1 on 2025-09-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0036_alter_permissaousuariodummy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissaousuariodummy',
            options={'permissions': [('logistica_perm', 'Permissão Logistica'), ('lastmile_b2c', 'LastMile (B2C)'), ('entrada_flfm', 'Entrada (Fulfillment)'), ('pode_gerenciar_filiais', 'Pode Gerenciar Filiais'), ('gestao_total', 'Gestão Total')], 'verbose_name': '--Personalizada--', 'verbose_name_plural': '--Personalizadas--'},
        ),
    ]
