# Generated by Django 5.2.1 on 2025-09-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0037_alter_permissaousuariodummy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaditionalinformation',
            name='cod_center',
            field=models.CharField(blank=True, null=True, verbose_name='Centro de Custos'),
        ),
    ]
