# Generated by Django 5.2.1 on 2025-09-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0038_groupaditionalinformation_cod_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='RomaneioReverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
