# Generated by Django 5.2.1 on 2025-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0039_romaneioreverse'),
    ]

    operations = [
        migrations.AddField(
            model_name='romaneioreverse',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='romaneioreverse',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
