# Generated by Django 5.2.1 on 2025-09-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0040_romaneioreverse_status_alter_romaneioreverse_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='romaneioreverse',
            name='status',
        ),
    ]
