# Generated by Django 5.2.1 on 2025-09-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0041_remove_romaneioreverse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaditionalinformation',
            name='cnpj',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CNPJ'),
        ),
    ]
