# Generated by Django 5.2.1 on 2025-09-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0042_groupaditionalinformation_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaditionalinformation',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
