# Generated by Django 5.2.1 on 2025-09-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0043_groupaditionalinformation_inscricao_estadual'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaditionalinformation',
            name='razao_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão Social'),
        ),
    ]
