# Generated by Django 5.2.1 on 2025-10-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0044_groupaditionalinformation_razao_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissaousuariodummy',
            options={'permissions': [('ti_interno', 'TI Interno'), ('logistica_perm', 'Permissão Logistica'), ('lastmile_b2c', 'LastMile (B2C)'), ('entrada_flfm', 'Entrada (Fulfillment)'), ('pode_gerenciar_filiais', 'Pode Gerenciar Filiais'), ('gestao_total', 'Gestão Total')], 'verbose_name': '--Personalizada--', 'verbose_name_plural': '--Personalizadas--'},
        ),
    ]
