# Generated by Django 5.2.1 on 2025-10-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0046_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, default='https://storage.googleapis.com/appandroidios-38136.appspot.com/Foto%20de%20perfil%20para%20redes%20sociais%20gradiente%20simples%20%284%29_02361f4b-38fb-485d-9bc6-548cb8a442e0.png', null=True),
        ),
    ]
