# Generated by Django 5.2.1 on 2025-10-30 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0047_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GroupAditionalInformationLegacy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_contato', models.CharField(max_length=100, verbose_name='Código do Contato')),
                ('gaiid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_entries', to='logistica.groupaditionalinformation', verbose_name='GAI (GroupAditionalInformation)')),
            ],
        ),
    ]
