# Generated by Django 5.2.1 on 2025-10-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0047_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
