# Generated by Django 5.2.1 on 2025-11-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0048_alter_userprofile_avatar'),
        ('logistica', '0050_alter_permissaousuariodummy_options'),
    ]

    operations = [
    ]
