# Generated by Django 5.2.1 on 2025-11-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0051_merge_20251123_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissaousuariodummy',
            options={'permissions': [('acesso_arancia', 'Acesso Arancia'), ('ti_interno', 'TI Interno'), ('logistica_perm', 'Permissão Logistica'), ('lastmile_b2c', 'LastMile (B2C)'), ('entrada_flfm', 'Entrada (Fulfillment)'), ('pode_gerenciar_filiais', 'Pode Gerenciar Filiais'), ('gestao_total', 'Gestão Total'), ('inst_simplified', 'Instalação Simplificada'), ('entrega_com_sap', 'Entrega com SAP'), ('checkin_principal', 'Check-in Principal'), ('products_management', 'Gerenciamento de Produtos')], 'verbose_name': '--Personalizada--', 'verbose_name_plural': '--Personalizadas--'},
        ),
    ]
