# Generated by Django 5.2.1 on 2026-01-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0053_alter_permissaousuariodummy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissaousuariodummy',
            options={'permissions': [('acesso_arancia', 'Acesso Arancia'), ('ti_interno', 'TI Interno'), ('logistica_perm', 'Permissão Logistica'), ('lastmile_b2c', 'LastMile (B2C)'), ('entrada_flfm', 'Entrada (Fulfillment)'), ('pode_gerenciar_filiais', 'Pode Gerenciar Filiais'), ('gestao_total', 'Gestão Total'), ('inst_simplified', 'Instalação Simplificada'), ('entrega_com_sap', 'Entrega com SAP'), ('checkin_principal', 'Check-in Principal'), ('checkout_principal', 'Check-out Principal'), ('products_management', 'Gerenciamento de Produtos'), ('gerente_estoque', 'Gerente de Estoque')], 'verbose_name': '--Personalizada--', 'verbose_name_plural': '--Personalizadas--'},
        ),
    ]
