# Generated by Django 5.2.1 on 2026-02-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0056_alter_permissaousuariodummy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaditionalinformation',
            name='codigo_ibge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código IBGE'),
        ),
    ]
