# Generated by Django 5.2.1 on 2026-03-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0057_groupaditionalinformation_codigo_ibge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupaditionalinformation',
            name='estado',
        ),
    ]
