# Generated by Django 5.2.1 on 2026-04-24 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0059_passwordresetcode_userpasswordcontrol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpasswordcontrol',
            options={'verbose_name': 'Controle de senha', 'verbose_name_plural': 'Controles de senha'},
        ),
        migrations.CreateModel(
            name='PasswordResetAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=255)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_access_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código único de acesso',
                'verbose_name_plural': 'Códigos únicos de acesso',
            },
        ),
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
