# Generated by Django 5.2.14 on 2026-05-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0061_alter_permissaousuariodummy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do acompanhamento')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug da URL')),
                ('link', models.URLField(max_length=500, verbose_name='Link do iframe')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Acompanhamento de Sistema',
                'verbose_name_plural': 'Acompanhamentos de Sistemas',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
