# Generated by Django 5.2.14 on 2026-05-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0062_acompanhamentosistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissaousuariodummy',
            options={'permissions': [('acesso_arancia', 'Acesso Arancia'), ('contas_privilegiadas', 'Acesso ao modulo de contas privilegiadas'), ('ti_interno', 'TI Interno'), ('logistica_perm', 'Permissão Logistica'), ('lastmile_b2c', 'LastMile (B2C)'), ('entrada_flfm', 'Entrada (Fulfillment)'), ('pode_gerenciar_filiais', 'Pode Gerenciar Filiais'), ('gestao_total', 'Gestão Total'), ('inst_simplified', 'Instalação Simplificada'), ('entrega_com_sap', 'Entrega com SAP'), ('checkin_principal', 'Check-in Principal'), ('checkout_principal', 'Check-out Principal'), ('products_management', 'Gerenciamento de Produtos'), ('estoque', 'Pode Visualizar Estoque'), ('gerente_estoque', 'Gerente de Estoque'), ('reverse', 'Reversa'), ('desinstalacao', 'Pode fazer Desinstalação'), ('full_checkin', 'Acesso Completo ao Check-in')], 'verbose_name': '--Personalizada--', 'verbose_name_plural': '--Personalizadas--'},
        ),
    ]
