# Generated by Django 5.2.14 on 2026-05-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0063_alter_permissaousuariodummy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
