# Generated by Django 5.2.1 on 2026-03-31 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroPadraoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_tela', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(default='Padrão do sistema', max_length=100)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filtro padrão da tela',
                'verbose_name_plural': 'Filtros padrão das telas',
            },
        ),
        migrations.CreateModel(
            name='PersonalPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '--Transp-Permission--',
                'verbose_name_plural': '--Transp-Permissions--',
                'permissions': [('controle_campo', 'Controle de Campo'), ('gerar_etiquetas', 'Gerar Etiquetas'), ('transp_menu', 'Mostrar menu transporte'), ('CC_admin', 'Mostrar menu administrativo'), ('CC_gerencial', 'Controle de campo gerencial'), ('controle_chamados', 'Controle de Chamados'), ('transportes', 'Permissão total para transporte')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('cod_base', models.CharField(max_length=50)),
                ('nome_unidade', models.CharField(blank=True, max_length=100, null=True)),
                ('documento', models.CharField(max_length=50)),
                ('profile', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiltroFavoritoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_tela', models.CharField(choices=[('consulta_os_transp', 'Consulta OS'), ('lista_viagens', 'Lista de Viagens')], max_length=100)),
                ('nome', models.CharField(default='Meu filtro favorito', max_length=100)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('favorito', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filtro favorito do usuário',
                'verbose_name_plural': 'Filtros favoritos dos usuários',
                'unique_together': {('usuario', 'chave_tela', 'nome')},
            },
        ),
    ]
