# Generated by Django 5.2.1 on 2026-04-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0002_alter_personalpermissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalpermissions',
            options={'permissions': [('controle_campo', 'Controle de Campo'), ('gerar_etiquetas', 'Gerar Etiquetas'), ('transp_menu', 'Mostrar menu transporte'), ('CC_admin', 'Mostrar menu administrativo'), ('CC_gerencial', 'Controle de campo gerencial'), ('controle_chamados', 'Controle de Chamados'), ('transportes', 'Permissão total para transporte')], 'verbose_name': '--Transp-Permission--', 'verbose_name_plural': '--Transp-Permissions--'},
        ),
    ]
