# Generated by Django 5.2.14 on 2026-05-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0004_alter_personalpermissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalpermissions',
            options={'permissions': [('controle_campo', 'Controle de Campo'), ('gerar_etiquetas', 'Gerar Etiquetas'), ('transp_menu', 'Mostrar menu transporte'), ('CC_admin', 'Mostrar menu administrativo'), ('CC_gerencial', 'Controle de campo gerencial'), ('controle_chamados', 'Controle de Chamados'), ('ver_transportes', 'Pode ver telas de transportes'), ('transportes', 'Permissão total para transporte'), ('CC_rotas', 'Acesso à rotas'), ('CC_roteirizacao', 'Acesso à roteirização')], 'verbose_name': '--Transp-Permission--', 'verbose_name_plural': '--Transp-Permissions--'},
        ),
    ]
