from crm.views.view_alerts import alert_list
from crm.views.view_billing import billing_edit, billing_list, billing_new
from crm.views.view_boards import (
    ajax_board_access_delete,
    ajax_board_reorder_columns,
    board_access,
    board_kanban,
)
from crm.views.view_clients import (
    ajax_client_delete,
    client_detail,
    client_edit,
    client_list,
    client_new,
)
from crm.views.view_contracts import (
    ajax_contract_file_delete,
    ajax_contract_file_upload,
    contract_detail,
    contract_edit,
    contract_list,
    contract_new,
)
from crm.views.view_dashboard import ajax_health, dashboard, validate_context
from crm.views.view_projects import (
    ajax_project_delete,
    ajax_project_member_delete,
    ajax_project_member_update,
    project_detail,
    project_edit,
    project_list,
    project_members,
    project_new,
)
from crm.views.view_settings import (
    ajax_settings_delete,
    settings_index,
    settings_priorities,
    settings_priority_edit,
    settings_priority_new,
    settings_service_type_edit,
    settings_service_type_new,
    settings_service_types,
    settings_status_task_edit,
    settings_status_task_new,
    settings_status_tasks,
)
from crm.views.view_tasks import (
    ajax_task_assign,
    ajax_task_attachment,
    ajax_task_comment,
    ajax_task_delete,
    ajax_task_move,
    ajax_task_watch,
    task_calendar,
    task_detail,
    task_edit,
    task_list,
    task_my,
    task_new,
)

__all__ = [
    'dashboard',
    'ajax_health',
    'validate_context',
    'client_list',
    'client_new',
    'client_detail',
    'client_edit',
    'ajax_client_delete',
    'contract_list',
    'contract_new',
    'contract_detail',
    'contract_edit',
    'ajax_contract_file_upload',
    'ajax_contract_file_delete',
    'billing_list',
    'billing_new',
    'billing_edit',
    'alert_list',
    'task_list',
    'task_my',
    'task_calendar',
    'task_new',
    'task_detail',
    'task_edit',
    'ajax_task_move',
    'ajax_task_assign',
    'ajax_task_comment',
    'ajax_task_attachment',
    'ajax_task_watch',
    'ajax_task_delete',
    'project_list',
    'project_new',
    'project_detail',
    'project_edit',
    'project_members',
    'ajax_project_member_update',
    'ajax_project_member_delete',
    'ajax_project_delete',
    'board_kanban',
    'board_access',
    'ajax_board_reorder_columns',
    'ajax_board_access_delete',
    'settings_index',
    'settings_service_types',
    'settings_service_type_new',
    'settings_service_type_edit',
    'settings_priorities',
    'settings_priority_new',
    'settings_priority_edit',
    'settings_status_tasks',
    'settings_status_task_new',
    'settings_status_task_edit',
    'ajax_settings_delete',
]
