from .dashboard_view import dashboard_view
from .iframe import extrair_enderecos_view, gerar_etiquetas_view, painel_Dashboard_view
from .criar_user_view import criar_user_view
from .mover_rota_view import mover_rota_view
from .ordenar_rota_view import ordenar_rota_view
from .ver_usuario_view import ver_usuario_view
from .View_session import config_context_view
from .scripting_view import scripting_view
from .views_controle_chamados.view_consulta_os_pend import consulta_os_pend
from .views_controle_chamados.view_lista_tecnicos import lista_tecnicos
from .views_controle_chamados.view_consulta_os import consulta_os
from .views_controle_chamados.view_detalhe_os import detalhe_os
from .views_transportes.view_detalhe_os import detalhe_os_transp, buscar_motoristas, buscar_veiculos
from .views_transportes.view_consulta_os_transp import consulta_os_transp
from .views_transportes.view_lista_viagens import lista_viagens, buscar_motoristas_travels
from .views_transportes.view_detalhe_viagem import detalhe_viagem
from .views_transportes.view_criar_os import criar_os_transp, buscar_locais
from .views_transportes.view_criar_localidade import skill_customer
from .views_transportes.view_criar_transportadora import skill_transport
from .views_transportes.view_criar_motorista import driver_ger
from .views_transportes.view_criar_veiculo import vehicle_ger
from .views_transportes.atribuir_motorista import atribuir_motorista_viagens_manual
